import AppKit

/// The mark's proportions, in one place.
///
/// Two very different pieces of code draw this shape — an `NSBezierPath` for
/// the menu bar, a SwiftUI `Shape` for the island's idle mark — and the whole
/// point of drawing it rather than shipping an asset is that it cannot drift.
/// Two sets of hand-copied ratios would put the drift straight back.
enum BrandGeometry {
    /// The notch is 1.39 times as wide as it is deep at every optical size, so
    /// the menu bar reads as the same object as the Dock.
    static let aspect: CGFloat = 78.0 / 56.0
    /// Top corners are barely rounded — detached from a display, the notch
    /// needs a hint of a corner or it reads as a crop.
    static let topCornerRatio: CGFloat = 0.103
    /// The status light, as a fraction of the mark's height.
    static let eyeRatio: CGFloat = 0.45
    /// How thick the menu bar cut's outline is, as a fraction of its height.
    ///
    /// Roughly the stroke an SF Symbol carries at menu bar size, which is the
    /// company this mark keeps.
    static let statusStrokeRatio: CGFloat = 0.10
}

/// The brand mark, drawn rather than shipped — the same reason the app icon is
/// generated by `scripts/make-icon.swift`: there is no binary asset that can
/// fall out of step with the geometry.
///
/// This is the menu bar cut of the mark: the notch drawn as an **outline**,
/// with the status light solid inside it.
///
/// ## Why it is not the filled shape
///
/// It used to be: an 18pt-tall solid silhouette with the light knocked out of
/// it. Two things were wrong with that. The menu bar's working area is 22pt
/// and a filled 16×16pt circle is what an Apple extra weighs up there, and
/// this shape is 1.39 times as wide as it is tall — so matching that weight is
/// a question of *area*, not of height, and an 18pt-tall version of it carries
/// nearly twice the ink of anything beside it. It did not read as a mark; it
/// read as a mistake. And a solid slab is the wrong company besides: almost
/// everything else in the menu bar is a stroked symbol.
///
/// Outlined at 14pt the mark keeps its silhouette, sheds most of its ink, and
/// stops being the loudest thing in the bar. The light is the one part that
/// stays solid — it is the only part that is saying anything, and it is what
/// makes this the same object as the mark living in the notch.
enum BrandMark {
    /// Proportions shared with the app icon — see `BrandGeometry`.
    private static let aspect = BrandGeometry.aspect

    /// The notch, sized for a status item.
    ///
    /// 14pt tall, so 20pt wide. See the type's note for where that comes from.
    static func statusItem(height: CGFloat = 14) -> NSImage {
        let size = CGSize(width: (height * aspect).rounded(), height: height)

        // Drawn through a handler rather than `lockFocus`, so AppKit redraws
        // the mark at whatever scale it is being asked for instead of scaling
        // one bitmap captured at launch, on whichever display happened to be
        // main at the time. A soft edge is the one thing a shape this small
        // cannot survive.
        let image = NSImage(size: size, flipped: false) { rect in
            let stroke = rect.height * BrandGeometry.statusStrokeRatio

            // Inset by half the stroke: `NSBezierPath` centres a stroke on the
            // path, so without this the outer half of it falls outside the
            // image and gets clipped to a flat edge.
            let shell = notchPath(in: rect.insetBy(dx: stroke / 2, dy: stroke / 2))
            shell.lineWidth = stroke
            shell.lineJoinStyle = .round
            // A template image keeps its alpha and macOS tints what is left, so
            // the shell can sit back from the light the same way it does in the
            // island — no second asset, and it works on a light bar too.
            NSColor.black.withAlphaComponent(0.78).setStroke()
            shell.stroke()

            let dotRadius = rect.height * BrandGeometry.eyeRatio / 2
            NSColor.black.setFill()
            NSBezierPath(ovalIn: CGRect(
                x: rect.midX - dotRadius, y: rect.midY - dotRadius,
                width: dotRadius * 2, height: dotRadius * 2
            )).fill()

            return true
        }

        image.isTemplate = true
        return image
    }

    /// The notch silhouette, fitted to a rect.
    ///
    /// The bottom corners are half the height, which is the same "radius =
    /// half the depth" rule the app icon uses.
    private static func notchPath(in rect: CGRect) -> NSBezierPath {
        let topCorner = rect.width * BrandGeometry.topCornerRatio
        let bottomCorner = rect.height / 2

        let notch = NSBezierPath()
        notch.move(to: CGPoint(x: rect.minX, y: rect.maxY - topCorner))
        notch.appendArc(
            from: CGPoint(x: rect.minX, y: rect.maxY),
            to: CGPoint(x: rect.maxX, y: rect.maxY), radius: topCorner
        )
        notch.appendArc(
            from: CGPoint(x: rect.maxX, y: rect.maxY),
            to: CGPoint(x: rect.maxX, y: rect.minY), radius: topCorner
        )
        notch.appendArc(
            from: CGPoint(x: rect.maxX, y: rect.minY),
            to: CGPoint(x: rect.minX, y: rect.minY), radius: bottomCorner
        )
        notch.appendArc(
            from: CGPoint(x: rect.minX, y: rect.minY),
            to: CGPoint(x: rect.minX, y: rect.maxY), radius: bottomCorner
        )
        notch.close()
        return notch
    }
}
