import AppKit

/// The mark's proportions, in one place.
///
/// Two very different pieces of code draw this shape — an `NSBezierPath` for
/// the menu bar, a SwiftUI `Shape` for the island's idle mark — and the whole
/// point of drawing it rather than shipping an asset is that it cannot drift.
/// Two sets of hand-copied ratios would put the drift straight back.
enum BrandGeometry {
    /// The notch is 1.39 times as wide as it is deep at every optical size, so
    /// the menu bar reads as the same object as the Dock.
    static let aspect: CGFloat = 78.0 / 56.0
    /// Top corners are barely rounded — detached from a display, the notch
    /// needs a hint of a corner or it reads as a crop.
    static let topCornerRatio: CGFloat = 0.103
    /// The status light, as a fraction of the mark's height.
    static let eyeRatio: CGFloat = 0.45
}

/// The brand mark, drawn rather than shipped — the same reason the app icon is
/// generated by `scripts/make-icon.swift`: there is no binary asset that can
/// fall out of step with the geometry.
///
/// This is the menu bar cut of the mark: the notch on its own, with the status
/// light *knocked out* instead of filled. A hole survives being a template
/// image, and a template is what lets macOS invert the icon for a light menu
/// bar without shipping a second asset.
enum BrandMark {
    /// Proportions shared with the app icon — see `BrandGeometry`.
    private static let aspect = BrandGeometry.aspect

    /// The notch, sized for a status item.
    ///
    /// 18pt is what AppKit gives a menu bar image before it starts scaling, and
    /// scaling is what blurs a shape whose whole job is a crisp edge.
    static func statusItem(height: CGFloat = 18) -> NSImage {
        let width = (height * aspect).rounded()
        let image = NSImage(size: CGSize(width: width, height: height))

        image.lockFocus()
        defer { image.unlockFocus() }

        // The bottom is half the height, which is the same "radius = half the
        // depth" rule the app icon uses.
        let topCorner = width * BrandGeometry.topCornerRatio
        let bottomCorner = height / 2

        let notch = NSBezierPath()
        notch.move(to: CGPoint(x: 0, y: height - topCorner))
        notch.appendArc(
            from: CGPoint(x: 0, y: height), to: CGPoint(x: width, y: height), radius: topCorner
        )
        notch.appendArc(
            from: CGPoint(x: width, y: height), to: CGPoint(x: width, y: 0), radius: topCorner
        )
        notch.appendArc(
            from: CGPoint(x: width, y: 0), to: CGPoint(x: 0, y: 0), radius: bottomCorner
        )
        notch.appendArc(
            from: CGPoint(x: 0, y: 0), to: CGPoint(x: 0, y: height), radius: bottomCorner
        )
        notch.close()

        let dotRadius = height * BrandGeometry.eyeRatio / 2
        notch.appendOval(in: CGRect(
            x: width / 2 - dotRadius, y: height / 2 - dotRadius,
            width: dotRadius * 2, height: dotRadius * 2
        ))
        notch.windingRule = .evenOdd

        NSColor.black.setFill()
        notch.fill()

        image.isTemplate = true
        return image
    }
}
